# Generated by Django 2.1.3 on 2018-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('order_name', models.CharField(max_length=20)),
                ('order_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('store_id', models.CharField(max_length=20)),
                ('order_info', models.ManyToManyField(to='myapp.OrderInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_menu',
            field=models.ManyToManyField(to='myapp.OrderMenu'),
        ),
    ]
