# Generated by Django 2.1.3 on 2018-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_orderlist_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_info',
            field=models.ManyToManyField(to='myapp.OrderInfo'),
        ),
    ]
